### ISSUE TITLE
Make unified release

### ISSUE THREAD

**Issue by svenstaro** [QtCurve/qtcurve#1]
Do you currently consider making a unified release from this repo which allows one to build all the ports from a single release?

**Comment by yuyichao** [comment]
Yes. Although it will take a while before this happens.

**Comment by yuyichao** [comment]
Basically having seperate repos and copies file here and there seems wrong to me, at least that's not how I usually do with git. Submodule may also do it but I don't think QtCurve is that big yet.
It should be able to compile now (well, although it seems that clang doesn't like c++0x.....) but I am still trying to pull out common code, have better compile options, keep each part in subdirectories so that it is easier to make split packages and that's why I said it would take a while. (Plus, it would be better to have release with new features rather than just combining different repos, I guess.)
