### ISSUE TITLE
Window positioning broken with qtcurve-qt5

### ISSUE THREAD

**Issue by kachelaqa** [QtCurve/qtcurve#3]
Using qtcurve-qt5 (2117), window positioning seems to ignore the title-bar and frame. This can result in the window being positioned beyond the edge of the screen (because of the negative offsets).

It looks like this problem was introduced with the recent [wmclass workaround](https://github.com/QtCurve/qtcurve-qt5/commit/79b0ab5795a0c9d65b8199c6041a2834faebfebc). When I comment out these lines (in _style/qtcurve_api.cpp_):

```
    if (widget->isWindow()) {
        XcbUtils::setWindowWMClass(widget->winId());
    }
```

the problem goes away.

Examining the information from xprop shows that the only significant difference seems to be that **WM_NORMAL_HINTS: window gravity** gets changed from **NorthWest** (which works) to **Static** (which is broken).

This is using openbox-3.5.2 with qt-5.1.1, on Arch Linux.

**Comment by yuyichao** [comment]
That part is already removed since it is fixed in Qt5 and it causes other problem as well.
I assume you are using my `qtcurve-qt5-git` package, please use the `qtcurve-git` package instead for now. I will update `qtcurve-qt5-git` after making the next release (should be soon) and making `qtcurve-git` a split package.

**Comment by yuyichao** [comment]
Relevant commit:
https://github.com/QtCurve/qtcurve/commit/eaf4893acfd8efa7114ebb414441e16a079d59e3#diff-9e16ad303024a8660bb55775dfd83a95R359
