### ISSUE TITLE
please make shadows optional   

### ISSUE THREAD

**Issue by eshkrig** [QtCurve/qtcurve#45]
Hi!
Sorry for my English.
QtCurve has very impressive features to provide for comfortable work at X terminals (LTSP) - simple widgets without gradients, etc.
While the window's shadow can be turned off, some widgets do not have that option.
Please make shadows optional (popup menus, combos, hints, etc.), it will be very helpful for X terminals in order to reduce traffic and improve responsiveness.
Many thanks.

**Comment by yuyichao** [comment]
While that is an option I'm planing to add once I'm ready for making change to the configure system, I don't really think the shadow drawing is causing a lot of traffic.

If you are talking about X forwarding. In the current implementation, the shadow is only drawn **ONCE** when the style is initialized and enabling the shadow on a window is as simple as a non-blocking X message, which is a lot simpler than any drawing preformed by Gtk and Qt themselves (it's as simple as setting the window title). The initial pixmaps are also very small and should be only tens of KB (and again is only done once for each app) (notice that this github page in which I am writing this reply is 28kB, the html part only). What I have seen before when my system is slow or when running X forward on a slow network is that the shadow may appear before the content of the windows. This actually means the shadow arrives a lot faster than the real content. (The same argument goes to window shadow, since there won't be any tranfic at all.)

If you are talking about sth like vnc, Then I think what you should do is turning of compositing. While the shadow area is a lot smaller than the window itself, I can imagine the damage events from shadows (which are transparent) can be a lot bigger than the opaque content. Turning off compositing will disable all non-opaque drawing and any effects which are cpu/gpu/bandwidth consuming. Although the initial drawing of the shadow is still preformed on the X server, it will never be shown on the screen and will not take any bandwidth.

**Comment by eshkrig** [comment]
Many thanks for the clarification - it changes everything.
Regards.

**Comment by luke-jr** [comment]
Please reopen this. I find the shadows ugly, and also do use VNC (but don't want to disable compositing).
